### ISSUE TITLE
Ember restless with Ember 2.0

### ISSUE THREAD

**Issue by TheRedDevil** [bustlelabs/ember-restless#62]
I am still learning ember so I am not sure if this has something with latest version, or with programming style, but I saw that in Ember 2.0 we would write

```
export default RL.Client.create({
  adapter: App.RESTAdapter
});
```

instead of

```
App.Client = RL.Client.create({
  adapter: App.RESTAdapter
});
```

but it seems that my client is then not recognised(if I write it in first way), as get request are made to localhost instead of url I specified in RESTAdapter class.

Second problem I have is that

```
import RL from 'ember-restless';
```

does not work for me, it says that module 'ember-restless' could not be found.

Any help would be appreciated, as I would like to continue using ember-restless.

**Comment by gdub22** [comment]
@TheRedDevil  This would be the es6 syntax:
```js
import { Client } from 'ember-restless';

export default Client.create({
  ...
});
```

**Comment by TheRedDevil** [comment]
I tried with this, and here's the situation:

If a put this import in my model class, I am getting following error in js console:

`Error: Could not find module `ember-restless` imported from `ember-test2/models/pol`

However, if I remove import from model class, leave adequate imports in RESTAdapter and Client definitions, there are no errors, but services are called on localhost:4200 instead on localhost:8080.

I will provide my definitions from js files here:

models/pol.js
```javascript
import { RL } from 'ember-restless'; // imports entire library

var Pol = RL.Model.extend({
  idPol: RL.attr('integer'),
  naziv: RL.attr('string')
});

Pol.reopenClass({
  resourceName: 'pol/e'
});

export default Pol;
```

adapters/application.js
```javascript
import { RL } from 'ember-restless';

export default RL.RESTAdapter.create({
  host: 'http://localhost:8080',
  namespace: 'zareps'
});
```

adapters/client.js
```javascript
import {RESTAdapter} from '../adapters/application';
import {Client} from 'ember-restless';

export default Client.create({
  adapter: RESTAdapter
});
```


routes/list-pol.js
```javascript
import Ember from 'ember';
import Pol from '../models/pol';

export default Ember.Route.extend({
  model() {
    return Pol.find();
  }
});
```

**Comment by TheRedDevil** [comment]
I also debuged this method

```javascript
/*
    RESTless Client initializer
   */
  Ember.Application.initializer({
    name: 'RESTless.Client',
    initialize: function(registry, application) {
      var applicationClient = application.Client;
      RESTless.set('client', applicationClient ? applicationClient : Client.create());
      application.addObserver('Client', application, function() {
        RESTless.set('client', this.Client);
      });
      RESTless.__container__ = application.__container__;
    }
  });
```

and it appears that **application.Client** is not defined

**Comment by gdub22** [comment]
Which ember version are you using?  2.0.0 - 2.0.1 releases should be working fine.  Looks like beta and canary are not working because application initializers have changed.  Working on an update to support them by the time 2.1.0 is released.

**Comment by TheRedDevil** [comment]
I tried with 2.0.0, 2.0.1 and 1.13.8, situation is the same. Btw, after bower install, is there anything more I should do to make package visible, maybe I missed something?

**Comment by Kasif32** [comment]
I have same problem. I also debuged the method mentioned above and saw that  application.Client is not defined. I tried with ember 2.2.0 and ember 1.13.11, had same result. 
In app.js I put 
```
App.RESTAdapter = RL.RESTAdapter.create({
  host: 'http://api.example.com',
  namespace: 'v1'
});

App.Client = RL.Client.create({
  adapter: App.RESTAdapter
});
```

I defined my model as 
```
import RL from 'ember-restless';

var Book = RL.Model.extend({
  bookName:   RL.attr('string'),
  authorName: RL.attr('string'),
  subject:   RL.attr('string')
});

Book.reopenClass({
  resourceName: 'book'
});

export default Book;
```
an in my route I tried to get books

```
var books = Book.find();
```
But it makes call to http://localhost:4200/books instead of http://api.example.com/v1/books.
What am I doing wrong?

**Comment by gdub22** [comment]
@Kasif32 You can't mix globals code with es6 modules.  

This works with 2.0+, you have to use an initializer now. I will update the docs.  Here is a full example:

app/initializers/restless.js
```js
import Ember from 'ember';
import { RESTAdapter, Client } from 'ember-restless';

export function initialize() {
  var application = arguments[1] || arguments[0];

  var adapter = RESTAdapter.create({
    host: 'http://api.example.com',
    namespace: 'v1'
  });

  // The missing piece
  application.set('Client', Client.create({
    adapter: adapter
  }));
}

export default {
  initialize,
  name: 'restless',
  before: 'RESTless.Client'
};
```

**Comment by Kasif32** [comment]
Got it, thank you!
