### ISSUE TITLE
Way to turn off URL entity pluralization

### ISSUE THREAD

**Issue by cfator** [bustlelabs/ember-restless#65]
The REST API I am integrating with does not have pluralized entity names in the URLs so would like a simple means to turn this off.  Currently I am just having to add every end point to the plurals config, like:

adapter.configure('plurals', {
    'someurl/entity': 'someurl/entity',
    'someurl/another-entity-name': 'someurl/another-entity-name'
});

Would like to do something like:
adapter.configure('plurals', false);

**Comment by gdub22** [comment]
@cfator try just overriding the adapter pluralize function:
```js
adapter.pluralize = function(resourceName) {
  return resourceName
}
```

**Comment by cfator** [comment]
Brilliant, Thank you!

-charlie
