### ISSUE TITLE
Why are you defining RESTless.lookupFactory twice?

### ISSUE THREAD

**Issue by meenie** [bustlelabs/ember-restless#71]
I noticed that you are defining `RESTless.lookupFactory` twice. Once in an `initializer` and again in an `instanceInitializer`.  We are still on Ember 1.13.13, slowing updating to 2.X and are trying to utilize `RESTless.lookupFactory`.  It looks like on 1.13.13, `_lookupFactory` isn't defined on `applicationInstance`. Maybe a later version? Or maybe that's just a bug?  In any case, removing that second initializer is what fixes our issue.

**Comment by gpoitch** [comment]
I honestly don't know.  Following whatever initializer rules were required at the time.
I do know that this has been used in production on 2.x without issue.
PRs welcome if you find a bug.

**Comment by gpoitch** [comment]
https://github.com/bustlelabs/ember-restless/commit/b44c705fb4bb00ed920c91cb39dbf1e8f1bf8be8
