### ISSUE TITLE
RESTless.lookupFactory not available when using ES6 imports

### ISSUE THREAD

**Issue by meenie** [bustlelabs/ember-restless#72]
When doing `import RL from 'ember-restless'`, `lookupFactory` is not defined.  But when using `RL` from the window, it is.

**Comment by gpoitch** [comment]
I believe lookupFactory is private.  Maybe even deprecated, moved, or removed in recent Ember?

This library is a bit unmaintained at this point.  We will accept PRs to fix any bugs though.
